image: tgstation/byond:latest

variables:
    BYOND_DME: "InterfaceQuery.dme"

stages:
    - build

build:
    stage: build
    script:
        - DreamMaker "$CI_PROJECT_DIR/$BYOND_DME"
    only:
        - master